### ISSUE TITLE
Error when change Posture mode

### ISSUE THREAD

**Issue by randauto** [googlecodelabs/android-foldable-codelab#6]
I got this error when change Posture mode of Emulator and this app crashed.

`java.lang.IllegalArgumentException: Bounds must be non zero
        at androidx.window.extensions.layout.FoldingFeature.validateFeatureBounds(FoldingFeature.java:125)
        at androidx.window.extensions.layout.FoldingFeature.<init>(FoldingFeature.java:95)
        at androidx.window.extensions.layout.WindowLayoutComponentImpl.getDisplayFeatures(WindowLayoutComponentImpl.java:227)
        at androidx.window.extensions.layout.WindowLayoutComponentImpl.getWindowLayoutInfo(WindowLayoutComponentImpl.java:176)
        at androidx.window.extensions.layout.WindowLayoutComponentImpl.onDisplayFeaturesChanged(WindowLayoutComponentImpl.java:168)
        at androidx.window.extensions.layout.WindowLayoutComponentImpl.$r8$lambda$XkTA_n58b4Cw9wT3LKS4oQrPVvA(Unknown Source:0)
        at androidx.window.extensions.layout.WindowLayoutComponentImpl$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at androidx.window.util.BaseDataProducer.notifyDataChanged(BaseDataProducer.java:49)
        at androidx.window.util.PriorityDataProducer$$ExternalSyntheticLambda0.run(Unknown Source:2)
        at androidx.window.util.BaseDataProducer.notifyDataChanged(BaseDataProducer.java:49)
        at androidx.window.common.SettingsDevicePostureProducer.access$100(SettingsDevicePostureProducer.java:37)
        at androidx.window.common.SettingsDevicePostureProducer$SettingsObserver.onChange(SettingsDevicePostureProducer.java:92)
        at android.database.ContentObserver.onChange(ContentObserver.java:169)
        at android.database.ContentObserver.onChange(ContentObserver.java:187)
        at android.database.ContentObserver.onChange(ContentObserver.java:202)
        at android.database.ContentObserver.lambda$dispatchChange$0$ContentObserver(ContentObserver.java:282)
        at android.database.ContentObserver$$ExternalSyntheticLambda0.run(Unknown Source:10)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7842)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)`

**Comment by bbbBBBSG** [comment]
> I got this error when change Posture mode of Emulator and this app crashed.
> 
> `java.lang.IllegalArgumentException: Bounds must be non zero at androidx.window.extensions.layout.FoldingFeature.validateFeatureBounds(FoldingFeature.java:125) at androidx.window.extensions.layout.FoldingFeature.<init>(FoldingFeature.java:95) at androidx.window.extensions.layout.WindowLayoutComponentImpl.getDisplayFeatures(WindowLayoutComponentImpl.java:227) at androidx.window.extensions.layout.WindowLayoutComponentImpl.getWindowLayoutInfo(WindowLayoutComponentImpl.java:176) at androidx.window.extensions.layout.WindowLayoutComponentImpl.onDisplayFeaturesChanged(WindowLayoutComponentImpl.java:168) at androidx.window.extensions.layout.WindowLayoutComponentImpl.$r8$lambda$XkTA_n58b4Cw9wT3LKS4oQrPVvA(Unknown Source:0) at androidx.window.extensions.layout.WindowLayoutComponentImpl$$ExternalSyntheticLambda0.run(Unknown Source:2) at androidx.window.util.BaseDataProducer.notifyDataChanged(BaseDataProducer.java:49) at androidx.window.util.PriorityDataProducer$$ExternalSyntheticLambda0.run(Unknown Source:2) at androidx.window.util.BaseDataProducer.notifyDataChanged(BaseDataProducer.java:49) at androidx.window.common.SettingsDevicePostureProducer.access$100(SettingsDevicePostureProducer.java:37) at androidx.window.common.SettingsDevicePostureProducer$SettingsObserver.onChange(SettingsDevicePostureProducer.java:92) at android.database.ContentObserver.onChange(ContentObserver.java:169) at android.database.ContentObserver.onChange(ContentObserver.java:187) at android.database.ContentObserver.onChange(ContentObserver.java:202) at android.database.ContentObserver.lambda$dispatchChange$0$ContentObserver(ContentObserver.java:282) at android.database.ContentObserver$$ExternalSyntheticLambda0.run(Unknown Source:10) at android.os.Handler.handleCallback(Handler.java:938) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:201) at android.os.Looper.loop(Looper.java:288) at android.app.ActivityThread.main(ActivityThread.java:7842) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)`

I have the same problem
